version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    env_file:
      - .env
    volumes:
      - ./database:/srv/flask_app/database
